### ISSUE TITLE
Sharebot issue

### ISSUE THREAD

**Issue by KillaQuack98** [Wizz1337/TikTokMassBotting#10]
Whenever I run the sharebot and enter lets say around 100000, it will randomly stop at 1k-10k

**Comment by baff3r** [comment]
Any errors?

**Comment by Wizz1337** [comment]
hm

**Comment by Wizz1337** [comment]
probably there are a error with threads 
when a error occurs with threads it will try to stop all threads 
i put a try on the line 111 & 118 when script create threads
download the new script
