### ISSUE TITLE
Issue with Views

### ISSUE THREAD

**Issue by c36sx** [Wizz1337/TikTokMassBotting#11]
Could you please fix the view bot everytime i try to open it, it says Proxie.txt not found

**Comment by Wizz1337** [comment]
what os are you using ?

**Comment by Wizz1337** [comment]
when its says "Failed to open Proxies.txt"
it will ask you to put the path 
i recommand to use direct path if not working

**Comment by c36sx** [comment]
> what os are you using ?

Windows

**Comment by baff3r** [comment]
just reinstall script
