### ISSUE TITLE
Issue with ViewBot

### ISSUE THREAD

**Issue by Nipa-Code** [Wizz1337/TikTokMassBotting#12]
Currently when I launch the code of ViewBot there's no output (Not sure if it's supposed to happen) and also it doesn't seem to work, no views go up. The SharesBot works fine.

**Comment by baff3r** [comment]
It was patched

**Comment by Nipa-Code** [comment]
> It was patched

Ah okay, that explains it.
Is there going to be update on the code for it

**Comment by baff3r** [comment]
Idk, you can ask creator

**Comment by Wizz1337** [comment]
i Updated, its not patched make sure to scrap proxy
idk if this screenshot can help you to config better
![image](https://user-images.githubusercontent.com/70026238/162792414-828bf685-06c5-409d-8371-cd82967bb907.png)
