### ISSUE TITLE
Problem view help

### ISSUE THREAD

**Issue by dos-argenta** [Wizz1337/TikTokMassBotting#13]

**Comment by dos-argenta** [comment]
![IMG_20220413_050211](https://user-images.githubusercontent.com/94066739/163091822-470f8049-f924-4363-82e6-e3e2d3a7389d.jpg)

**Comment by baff3r** [comment]
link:
n
http
3
1000

**Comment by Wizz1337** [comment]
link is wrong
link must be like : https://www.tiktok.com/@xxx/video/123
