### ISSUE TITLE
Question about the APIs

### ISSUE THREAD

**Issue by ezzcodeezzlife** [Wizz1337/TikTokMassBotting#14]
Just a quick question. I understand everything about the code, but what exactly are these APIs that get called in the "SendViews" Function? They dont look official. So what are they doing?

```
ApiDomain   = ["api19.tiktokv.com", "api.toutiao50.com", "api19.toutiao50.com", "api19-core-c-alisg.tiktokv.com"]
```

Thanks for the help

@Wizz1337

**Comment by Wizz1337** [comment]
its private apis of tiktok you cant get it easily
