### ISSUE TITLE
hz#3623 is selling ur tool on tiktok

### ISSUE THREAD

**Issue by fetixdxd** [Wizz1337/TikTokMassBotting#17]
![image](https://user-images.githubusercontent.com/103859133/163787771-b0da4da8-8519-4fa1-ac07-5843d2934f29.png)

**Comment by fetixdxd** [comment]
he's saying his friend made it but he skidded it

**Comment by b6m** [comment]
can confirm

**Comment by Wizz1337** [comment]
> ![image](https://user-images.githubusercontent.com/103859133/163787771-b0da4da8-8519-4fa1-ac07-5843d2934f29.png)

can you send me his discord server, username & discim, id ?

**Comment by b6m** [comment]
hz#3623 | 933330648373006406 | https://discord.gg/W7f7Y5Zn

**Comment by b6m** [comment]
@Wizz1337

**Comment by Wizz1337** [comment]
thanks
