### ISSUE TITLE
scammers selling it for $20

### ISSUE THREAD

**Issue by 00a1** [Wizz1337/TikTokMassBotting#20]
https://discord.gg/9kdf2DAc

**Comment by 00a1** [comment]
![Screenshot_102](https://user-images.githubusercontent.com/50469859/164154711-91ae7056-10c8-41d8-b8f3-96aa02f095dd.png)

**Comment by 00a1** [comment]
![Screenshot_103](https://user-images.githubusercontent.com/50469859/164154892-4fd94e4f-1fef-4feb-a562-b3ff2ef26f6f.png)

**Comment by Wizz1337** [comment]
thanks added to scammers
