### ISSUE TITLE
Skid

### ISSUE THREAD

**Issue by b6m** [Wizz1337/TikTokMassBotting#21]
discord.gg/oxity | user id : 954372342887378944 | Krsxz#0001 | guild id : 965193120700596244

![image](https://user-images.githubusercontent.com/65096390/164184899-b4c8fe1c-4c7d-4337-89c9-70ba079f0cf0.png)
![image](https://user-images.githubusercontent.com/65096390/164184907-7a91006f-de2c-4f18-96dd-973af0a22fca.png)

**Comment by Wizz1337** [comment]
thanks to you i will add it
