### ISSUE TITLE
Skid Selling

### ISSUE THREAD

**Issue by b6m** [Wizz1337/TikTokMassBotting#25]
![image](https://user-images.githubusercontent.com/65096390/164446969-167a9c69-d4c5-4cbe-817a-fc33d32170c7.png)
![image](https://user-images.githubusercontent.com/65096390/164446979-5f655ff2-cc97-4603-b8eb-b3b4f77af28f.png)

151k#6661 | ID : 814508737745911878 | Guild: idk yet | Guild Id: idk yet, i'll update this issue when i found out

**Comment by b6m** [comment]
https://vm.tiktok.com/ZTdXXhX2M

**Comment by b6m** [comment]
read comments, he's selling it ^

**Comment by Wizz1337** [comment]
lol nice skid
