### ISSUE TITLE
it blocks at this moment

### ISSUE THREAD

**Issue by snowdqdzq** [Wizz1337/TikTokMassBotting#27]
![image](https://user-images.githubusercontent.com/52897962/164548552-3d6941c7-90ce-482f-bf66-dfcff580c959.png)

**Comment by Wizz1337** [comment]
idk

**Comment by Just-Haze** [comment]
can i ask where can i get proxy? and how to put it?

**Comment by hugolebihan56** [comment]
same problem

**Comment by Wizz1337** [comment]
download the new one
