### ISSUE TITLE
hit 

### ISSUE THREAD

**Issue by william2112345** [Wizz1337/TikTokMassBotting#32]
how long do i need to wait for a hit its been a very long time and i have not gotten a hit. is there a way to fix this

**Comment by Wizz1337** [comment]
how many threads,timeout did you, did you enter yes for proxy scrap if yes what proxy type did you choose ?

**Comment by william2112345** [comment]
i am using socks4 but i tried all the other ones to  my timeout is 3 and i picked yes and 200 threads

**Comment by Wizz1337** [comment]
download the new one
