### ISSUE TITLE
Can I get a hand?

### ISSUE THREAD

**Issue by Mgamer1300** [Wizz1337/TikTokMassBotting#33]
![image_2022-04-21_234030592](https://user-images.githubusercontent.com/44687849/164591682-83da064b-0265-4c7b-b5bb-8086ee33ceb7.png)

Also happens with ViewBot
can i get some help?

**Comment by william2112345** [comment]
you need to open cmd and download

**Comment by Waresilva** [comment]
happens for me to

**Comment by Waresilva** [comment]
what should i download

**Comment by catzsec** [comment]
Type exactly this,

`
pip install requests
`

**Comment by Wizz1337** [comment]
try that : pip install requests pystyle
to install all required lib
