### ISSUE TITLE
Very High Cpu Usage on 40 Threads, Sharebot

### ISSUE THREAD

**Issue by Catchii** [Wizz1337/TikTokMassBotting#36]
Everything Above 40 Threads Maxes Out My CPU To 100% The Python Programm is Taking 60% with 40 Threads

is there any fix for that?

Win 11

**Comment by Wizz1337** [comment]
what is your cpu ?

**Comment by Catchii** [comment]
intel i5 9400H 4 cores

https://catchii.wtf/images/catchii/73482

**Comment by Wizz1337** [comment]
bruh its normal bro
your cpu is shit
