### ISSUE TITLE
I found some copy cats you can do whatever you want with them i only went to the 10th page of github.

### ISSUE THREAD

**Issue by 00a1** [Wizz1337/TikTokMassBotting#37]
https://github.com/moxy-code/TikTok-Share-Bot
https://github.com/CrystalEU/ShareBot-Tiktok
https://github.com/zenty404/TikTok_Share_Bot
https://github.com/gsventu/Tiktok-Share-Bot
https://github.com/ladas2000/tiktok-sharebot | no Credit
https://github.com/CrystalEU/Viewbot-Tiktok
https://github.com/2wz/tiktok-shares-bot
https://github.com/floppa1337/Tiktok-Sharebot
https://github.com/dos-argenta/TikTokShareBot-SpiritOfStalker
https://github.com/drezhack/TikTok-Shares
https://github.com/KazamaOnGithub/TikTok_ShareBoost

**Comment by Wizz1337** [comment]
Thanks !
