### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by andress134** [Wizz1337/TikTokMassBotting#4]
It look dead,  0 views

sh: 1: title: not found
sh: 1: title: not found
sh: 1: sh: 1: sh: 1: title: not found
title: not found
title: not found
sh: 1: sh: 1: title: not found
title: not found  

and just get it, zero views tried with socks5 and http proxies but still 0 views

@Wizz1337

**Comment by Wizz1337** [comment]
im fixing rn
