### ISSUE TITLE
Viewbot broken

### ISSUE THREAD

**Issue by re6chwet** [Wizz1337/TikTokMassBotting#40]
The viewbot never actually sends the requests and gets stuck.
![Capture](https://user-images.githubusercontent.com/84555294/164773921-74257dad-13bd-4fde-bd6d-110b5d23afab.PNG)

**Comment by MrMarios** [comment]
Hello 
I was wondering if you could help me figure out how the coding with the bot works and put in work.
Im not keen on coding so i dont have an idea how to use it i have a laptop that i can use.
Thank you for your time please if you see this contact me i would appreciate it a lot.😌
Also my discord is Mr.4K#6522

**Comment by hugolebihan56** [comment]
same problem

**Comment by Wizz1337** [comment]
i will check now what the problem

**Comment by hugolebihan56** [comment]
it seems req = r.post(URI, headers=headers, data=Data, proxies=proxy, timeout=timeout, stream=True, verify=False) doesn't work

**Comment by Wizz1337** [comment]
download the new one
