### ISSUE TITLE
the view bot never gets a hit 

### ISSUE THREAD

**Issue by william2112345** [Wizz1337/TikTokMassBotting#42]
whenever i run view bot it never gets a hit. i have tried everthing

**Comment by Just-Haze** [comment]
bro try installing Python on MicrosoftStore after that Right Click on the View.py or Share.py and open it with the microsoft one that should fix the problem

**Comment by calebidklol** [comment]
Same, It just never sends anything. My console has just said this for the past 5 minutes. 
Working But Slow !
Video Link > 
Amount (0=inf) > 0
Scrap Proxies [y/n] > n
Proxy Type > Socks5
Proxy Timeout > 0
Thread Amount > 1000

**Comment by Wizz1337** [comment]
download the new one
