### ISSUE TITLE
ViewBot.py

### ISSUE THREAD

**Issue by 0jrv** [Wizz1337/TikTokMassBotting#44]
![image](https://user-images.githubusercontent.com/87977572/164791077-22c1552b-50d5-4df8-93b2-8696aaeeabc0.png)
what happens after this part?

**Comment by Wizz1337** [comment]
must wait for a hit

**Comment by 0jrv** [comment]
well ive been waiting there wasnt any hits

**Comment by 0jrv** [comment]
ill try again tomorrow

**Comment by Wizz1337** [comment]
join https://discord.gg/RHZkC3PAhJ
