### ISSUE TITLE
Issue with the ViewBot script 

### ISSUE THREAD

**Issue by sociallyakwardfrog** [Wizz1337/TikTokMassBotting#53]
Tried running it with normal privileges and with admin privileges but it stops at the "Hit are not counted
Bot Started check your video view in 5 minute !" prompt and I've tried http, socks4 and socks5 with no results and i know for a fact that no anti-virus is interfering with the script

**Comment by CoolGuyMK** [comment]
> Tried running it with normal privileges and with admin privileges but it stops at the "Hit are not counted Bot Started check your video view in 5 minute !" prompt and I've tried http, socks4 and socks5 with no results and i know for a fact that no anti-virus is interfering with the script

+++1

**Comment by Wizz1337** [comment]
its patched
