### ISSUE TITLE
ShareBot.py Stopping and resuming

### ISSUE THREAD

**Issue by Oskarhn** [Wizz1337/TikTokMassBotting#63]
When I run ShareBot.py it sends probably 1000 shares then it stops for like 5 mins, and then continues to send 500 before stopping. It just keeps doing this. I double checked with the YouTube video to see if I did anything wrong, but I didn't. The program works, but the problem persists. I'm running the program on Linux if it matters.

**Comment by Wizz1337** [comment]
maybe your network ?
