### ISSUE TITLE
share bot patched

### ISSUE THREAD

**Issue by c36sx** [Wizz1337/TikTokMassBotting#65]
patched

**Comment by Aquakun1** [comment]
I don't think is patched , because you can't share anymore even with other platforms

**Comment by Aquakun1** [comment]
> I don't think is patched , because you can't share anymore even with other platforms

When you share, it doesn't count

**Comment by Auax** [comment]
It doesn't count for me either. It's probably patched.

**Comment by Justinray7** [comment]
it's not working anymore

**Comment by Auax** [comment]
Yeah, they must've fixed the issue after watching videos with 10B shares

**Comment by Sardiny-dev** [comment]
It's pached

**Comment by louisgaming** [comment]
Hmm Is there any fix to it? I mean, the plays work so thats good i guess.

**Comment by Wisam4441** [comment]
wdym by plays?

**Comment by louisgaming** [comment]
Plays = views

**Comment by SenseDev1337** [comment]
it will be fixed soon

**Comment by louisgaming** [comment]
> it will be fixed soon

How soon?

**Comment by Wizz1337** [comment]
discord.gg/devcenter
patched
