### ISSUE TITLE
View Bot issue

### ISSUE THREAD

**Issue by Mystic-rgb** [Wizz1337/TikTokMassBotting#69]
I have no idea if im stupid or what but when i try to use the view bot it just does not work for me. If someone could help me out that would be awesome. because ive tried to do the proxies thing and it still does not work.

**Comment by Aljoberg** [comment]
For me, i kinda copied the share bot.py code and then changed share_delta to play_delta and it worked lmao
It still works for me Soo it's probably worth trying it

**Comment by Mystic-rgb** [comment]
lol this is the 69th issue. do you have discord so we can talk and help me out on it

**Comment by Mystic-rgb** [comment]
Mystie#6666

**Comment by Mystic-rgb** [comment]
oh well i just realized what you said. thanks a lot if you still wanna add me on discord you can and we can talk some more on there

**Comment by Mystic-rgb** [comment]
> For me, i kinda copied the share bot.py code and then changed share_delta to play_delta and it worked lmao It still works for me Soo it's probably worth trying it

I just tried it and still no luck

**Comment by Aljoberg** [comment]
Ok i sent friend request

**Comment by Wizz1337** [comment]
patched
