### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\BobSh\OneDrive\Desktop\dont open\dont  open - Copy (69)\TikTokMassBotting-main\Main.py", line 6, in <module>     from urllib3.exceptions import InsecureRequestWarning ModuleNotFoundError: No module named 'urllib3'

### ISSUE THREAD

**Issue by Bobbiezbuilder** [Wizz1337/TikTokMassBotting#77]
U have deleted the sharebot and the veiw bot from the last update u did to the files

**Comment by Bobbiezbuilder** [comment]
Traceback (most recent call last):
  File "C:\Users\BobSh\OneDrive\Desktop\dont open\dont  open - Copy (69)\TikTokMassBotting-main\Main.py", line 6, in <module>
    from urllib3.exceptions import InsecureRequestWarning
ModuleNotFoundError: No module named 'urllib3'

**Comment by veast-network** [comment]
run `pip install requests pystyle`
