### ISSUE TITLE
Almost no views are sent

### ISSUE THREAD

**Issue by Aljoberg** [Wizz1337/TikTokMassBotting#79]
Shares work pretty well, but you only get like 1 view per 1000 requests ...

**Comment by popcrocks** [comment]
same

**Comment by Aljoberg** [comment]
it works better with a good pc and a lot of threads but still really slow (unlike shares)

**Comment by ayamkv** [comment]
it is really really slow

**Comment by ShireDev** [comment]
Sorry but currently the API is slow so this is normal
