### ISSUE TITLE
Multi services

### ISSUE THREAD

**Issue by andress134** [Wizz1337/TikTokMassBotting#8]
Hello man. @Wizz1337 
Can you improve this script to use that websites for followers / views / likes
Adding arguments for all methods
multi methods like ' shares - likes - views - view-v1 - views-v2 etc

so using this websites to get that services
you can make a script that will use all in one?

if choice method 'views-v1' to call back to homedecoratione.com  etc
https://homedecoratione.com/
https://www.instafollowers.co/free-tiktok-views
https://fbsub.de/

also can this script be improved also to generate fake views on youtube?

**Comment by Wizz1337** [comment]
there are two way to make this
first with selenium (shit)
twice with api (too difficult there are temp params and more)
