### ISSUE TITLE
idk how to call this one

### ISSUE THREAD

**Issue by ssjblue-xxx** [Wizz1337/TikTokMassBotting#86]
why does it shows that there are 100k shares sent (my pov) (btw i had 10.2 millions shares with the old version) but when iu check the tiktok its stuck at 10.2 millions, can anyone help please ?

**Comment by ShaunB56** [comment]
Not every share it counts is actually a hit. The number of "shares" it shows in the console, is just how many requests the script sent, not how many actually worked.

**Comment by Aljoberg** [comment]
Yeah because of rate limits and bad API

**Comment by ssjblue-xxx** [comment]
ohhhh
