### ISSUE TITLE
Error(ViewBot)

### ISSUE THREAD

**Issue by baff3r** [Wizz1337/TikTokMassBotting#9]
![Screenshot_2022-04-07-00-09-44-226_com termux](https://user-images.githubusercontent.com/102964988/162071520-89525361-c9c4-4118-bb80-11d2ab0837d5.png)
Views are not credited

**Comment by andress134** [comment]
> ![Screenshot_2022-04-07-00-09-44-226_com termux](https://user-images.githubusercontent.com/102964988/162071520-89525361-c9c4-4118-bb80-11d2ab0837d5.png) Views are not credited

STOP USED IT 
IM USING THIS SCRIPT ON MY ACCOUNT WITH 300 FOLLOWERS (YES KNOW NOT MUCH)
AND MY ACCOUNT NOW IS RESTRICTED LOL WTF
@Wizz1337  yo man why tiktok ban my acc ? is ilegal to use this tool?

**Comment by baff3r** [comment]
Up

**Comment by baff3r** [comment]
Up

**Comment by Wizz1337** [comment]
its working for me ..

**Comment by Wizz1337** [comment]
did you have

**Comment by baff3r** [comment]
Tyy, it working, but too slow:(
