### ISSUE TITLE
No work

### ISSUE THREAD

**Issue by Neast1337** [Wizz1337/TikTokMassBotting#91]
it doesn't work for me

**Comment by Aljoberg** [comment]
can you explain what doesn't work? 
remember, shares are patched and views are working, but slowly (check the discord server)

**Comment by Auax** [comment]
I think TikTok patched the API

**Comment by Aljoberg** [comment]
Mhm, true.
Let's hope wizz finds a new one :>

**Comment by Neast1337** [comment]
no share and sight no longer works
